### ISSUE TITLE
send duplicate messages 

### ISSUE THREAD

**Issue by salexch** [chalettu/pushwoosh-nodejs#1]
in this.sendMessage
line #50: var sendOptions = defaultConfig;

not cloning the defaultConfig
I fixed it with underscorejs

to 

var sendOptions = _.extend({}, defaultConfig);

this fixed the bug.

thank you for sharing the module!!

**Comment by oriefrati** [comment]
Hi,
i think i have same issue, you problem was that the plugin was sending new push message and also the old one again?
something like:

Send Msg 1
Receive Msg 1

Send Msg 2
Receive Msg 1
Receive Msg 2

Send Msg 3
Receive Msg 1
Receive Msg 2
Receive Msg 3

**Comment by salexch** [comment]
It was a long time ago.. sounds like a problem I had

**Comment by oriefrati** [comment]
OK i will try your fix.

Thanks!.
